# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TT Nyhetsbyrån AB
email: utvecklare@tt.se
description: > # this means to ignore newlines until "baseurl:"
   TT Nyhetsbyrån technical specifications and other useful stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spec.tt.se" # the base hostname & protocol for your site
twitter_username: ttnyhetsbyran
github_username:  ttab

# Build settings
markdown: kramdown
